[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_program = "LUMPd26Acz4wqS8EBuoxPN2zhwCUF4npbkrqhLbM9AL"

[programs.mainnet]
solana_program = "LUMPd26Acz4wqS8EBuoxPN2zhwCUF4npbkrqhLbM9AL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/lumenless/program_deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
